# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'showcase_mvvm' do
  pod 'RxSwift'
  pod 'RxRetroSwift'
  pod 'Alamofire', '~> 5.0.0-beta.5'
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for showcase_mvvm

  target 'showcase_mvvmTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'showcase_mvvmUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
